name: Default workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.4.0
      - name: Set version
        run: |
          poetry version
          echo "SDK_VERSION=\"$(poetry version | awk '{print $NF}')\"" > telq/util/version.py
          cat telq/util/version.py
      - name: Install dependencies
        run: |
          poetry install
      - name: Build
        run: |
          poetry build
          poetry install
      - name: Run tests
        env:
          api_id: ${{ secrets.TEST_API_ID }}
          api_key: ${{ secrets.TEST_API_KEY }}
          base_url: ${{ secrets.TEST_BASE_URL }}
        run: |
          poetry run pytest
